package com.example.demo.domain;

public class User {
    public User(String mail, String password) {
        this.mail = mail;
        this.password = password;
    }

    private int id; // just used to demo retrieval of autogenerated key in UserMapper
    private String mail;
    private String password; // Should be hashed and secured

    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword( String password ) {
        this.password = password;
    }

    public int getId() {
        return id;
    }

    public void setId( int id ) {
        this.id = id;
    }

}